Rules separation and now handling paired and single data
sequana/depletion pull request #3
Opened 2023-02-02 15:56 UTC by khourhin

2023-02-02 16:27 UTC, ddesvillechabrol commented on sequana_pipelines/depletion/depletion.rules
> +                  "single": "-f4"}}
Je suis pas contre un peu de commentaire pour les flags. Je ne sais plus du tout ce que ça fait.

2023-02-02 16:27 UTC, ddesvillechabrol commented on sequana_pipelines/depletion/depletion.rules
> +    threads: 2
Je sais pas si ce thread en dur est voulu

2023-02-02 16:27 UTC, ddesvillechabrol commented on sequana_pipelines/depletion/depletion.rules
> +        bioconvert bam2fastq {input.bam} {wildcards.sample}/{wildcards.sample}_filtered.fastq.gz --force
Pourquoi tu utilise pas ton `{output}` ? Il y a pas un soucis si c'est paired ici ?

2023-02-02 16:27 UTC, ddesvillechabrol commented on sequana_pipelines/depletion/schema.yaml
> +    "filter":
Je me demande si faut pas mettre samtools dans le nom, au moins on sait de quoi il en retourne.

2023-02-02 16:27 UTC, ddesvillechabrol commented on sequana_pipelines/depletion/schema.yaml
> +                type: str
Il manque pas des `required` ?

2023-02-02 16:29 UTC, cokelaer commented on sequana_pipelines/depletion/depletion.rules
> +                  "single": "-f4"}}
pareil :-)

2023-02-02 16:29 UTC, cokelaer commented on sequana_pipelines/depletion/depletion.rules
> +    threads: 2
on peut le mettre dans le config en effet

2023-02-02 16:34 UTC, cokelaer requested changes
les containers ça serait bien comme ça on peut enchainer avec un CI apptainer

2023-02-02 16:34 UTC, cokelaer commented on sequana_pipelines/depletion/config.yaml
> +    options: -T 30 -M
on pourrait avoir les options dans le config et le thread également

2023-02-02 16:34 UTC, cokelaer commented on sequana_pipelines/depletion/depletion.rules
> +    shell:
on peut ajouter le container ici

2023-02-02 16:34 UTC, cokelaer commented on sequana_pipelines/depletion/depletion.rules
> +        """
ici aussi on pourrait utiliser un container bioconvert. essayons celui ci: 
https://zenodo.org/record/7470179/files/bioconvert_0.6.2.img a priori ça doit fonctionner

2026-04-01 08:24 UTC, cokelaer commented
diverged a lot. fixed in latest version.

2026-04-01 08:24 UTC, closed without merging